### ISSUE TITLE
Add Sponsors and Speakers

### ISSUE THREAD

**Issue by smithsa** [elm-in-the-spring/conference-2020#3]

**Comment by arsduo** [comment]
I've added Hubtran as a sponsor in b0d89ffdadb60f51ee7a4a0a9d391b21f2eda01c.

For the speakers, I've asked the speakers for the two invited talks for their bios/photos/links. If we don't have them when everything else is ready, I think it'd be okay to put a "Speaker info coming soon!" banner there. 

Either way, we should definitely have a "Want to share your idea? Submit to our CFP!" (or whatever wording) button in that section as well.
